os: linux
dist: trusty
language: c
compiler: gcc

script:
  - cmake . -D BUILD_ALL=ON -D CMAKE_BUILD_TYPE:String="Coverage"
  - make
  - ctest -T Test -VV
  - ctest -T MemCheck -VV
  - cat Testing/Temporary/MemoryChecker.*.log || exit 0

addons:
  apt:
    packages:
    - valgrind
