os: linux
dist: trusty
language: c
compiler: gcc

script:
  - cmake . -DBUILD_ALL=ON -DCMAKE_BUILD_TYPE:String="Coverage"
  - make
  - ctest -T Test -VV
  - ctest -T MemCheck -VV
  - cat Testing/Temporary/MemoryChecker.*.log || exit 0
  - ctest -T Coverage -V

addons:
  apt:
    packages:
    - valgrind
